# Generated by Django 6.0.4 on 2026-04-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
